name: planner
description: "Course work as a planner"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  crypto: ^3.0.3
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  googleapis: ^13.1.0
  material: ^1.0.0+2
  pointycastle: ^3.9.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  syncfusion_flutter_calendar: ^25.1.38
  table_calendar: ^3.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
